package com.example.transportsystem.transportsystem.controller;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@CrossOrigin(origins = "http://localhost:3000")
public class TransportDestinationController {

	
	
	private static final List<String> indianCities = Arrays.asList(
            "Mumbai, Maharashtra",
            "Delhi, Delhi",
            "Bangalore, Karnataka",
            "Hyderabad, Telangana",
            "Chennai, Tamil Nadu",
            "Kolkata, West Bengal",
            "Surat, Gujarat",
            "Pune, Maharashtra",
            "Jaipur, Rajasthan",
            "Lucknow, Uttar Pradesh",
            "Kanpur, Uttar Pradesh",
            "Nagpur, Maharashtra",
            "Visakhapatnam, Andhra Pradesh",
            "Indore, Madhya Pradesh",
            "Thane, Maharashtra",
            "Bhopal, Madhya Pradesh",
            "Patna, Bihar",
            "Vadodara, Gujarat",
            "Ghaziabad, Uttar Pradesh",
            "Ludhiana, Punjab",
            "Agra, Uttar Pradesh",
            "Nashik, Maharashtra",
            "Faridabad, Haryana",
            "Meerut, Uttar Pradesh",
            "Rajkot, Gujarat",
            "Varanasi, Uttar Pradesh",
            "Srinagar, Jammu and Kashmir",
            "Aurangabad, Maharashtra",
            "Dhanbad, Jharkhand",
            "Amritsar, Punjab",
            "Navi Mumbai, Maharashtra",
            "Allahabad, Uttar Pradesh",
            "Ranchi, Jharkhand",
            "Howrah, West Bengal",
            "Coimbatore, Tamil Nadu",
            "Jabalpur, Madhya Pradesh",
            "Gwalior, Madhya Pradesh",
            "Vijayawada, Andhra Pradesh",
            "Jodhpur, Rajasthan",
            "Madurai, Tamil Nadu",
            "Raipur, Chhattisgarh",
            "Kota, Rajasthan",
            "Guwahati, Assam",
            "Chandigarh, Chandigarh",
            "Solapur, Maharashtra",
            "Hubli-Dharwad, Karnataka",
            "Bareilly, Uttar Pradesh",
            "Moradabad, Uttar Pradesh",
            "Mysore, Karnataka",
            "Gurgaon, Haryana",
            "Aligarh, Uttar Pradesh",
            "Jalandhar, Punjab",
            "Tiruchirappalli, Tamil Nadu",
            "Bhubaneswar, Odisha",
            "Salem, Tamil Nadu",
            "Warangal, Telangana",
            "Guntur, Andhra Pradesh",
            "Bhiwandi, Maharashtra",
            "Saharanpur, Uttar Pradesh",
            "Gorakhpur, Uttar Pradesh",
            "Bikaner, Rajasthan",
            "Amravati, Maharashtra",
            "Noida, Uttar Pradesh",
            "Jamshedpur, Jharkhand",
            "Bhilai, Chhattisgarh",
            "Cuttack, Odisha",
            "Firozabad, Uttar Pradesh",
            "Kochi, Kerala",
            "Nellore, Andhra Pradesh",
            "Bhavnagar, Gujarat",
            "Dehradun, Uttarakhand",
            "Durgapur, West Bengal",
            "Asansol, West Bengal",
            "Rourkela, Odisha",
            "Nanded, Maharashtra",
            "Kolhapur, Maharashtra",
            "Ajmer, Rajasthan",
            "Akola, Maharashtra",
            "Gulbarga, Karnataka",
            "Jamnagar, Gujarat",
            "Ujjain, Madhya Pradesh",
            "Loni, Uttar Pradesh",
            "Siliguri, West Bengal",
            "Jhansi, Uttar Pradesh",
            "Ulhasnagar, Maharashtra",
            "Jammu, Jammu and Kashmir",
            "Sangli-Miraj & Kupwad, Maharashtra",
            "Mangalore, Karnataka",
            "Erode, Tamil Nadu",
            "Belgaum, Karnataka",
            "Ambattur, Tamil Nadu",
            "Tirunelveli, Tamil Nadu",
            "Malegaon, Maharashtra",
            "Gaya, Bihar",
            "Jalgaon, Maharashtra",
            "Udaipur, Rajasthan",
            "Maheshtala, West Bengal",
            "Tirupur, Tamil Nadu",
            "Davanagere, Karnataka",
            "Kozhikode, Kerala",
            "Kurnool, Andhra Pradesh",
            "Rajpur Sonarpur, West Bengal",
            "Rajahmundry, Andhra Pradesh",
            "Bokaro Steel City, Jharkhand",
            "South Dumdum, West Bengal",
            "Bellary, Karnataka",
            "Patiala, Punjab",
            "Gopalpur, West Bengal",
            "Agartala, Tripura",
            "Bhagalpur, Bihar",
            "Muzaffarnagar, Uttar Pradesh",
            "Bhatpara, West Bengal",
            "Panihati, West Bengal",
            "Latur, Maharashtra",
            "Dhule, Maharashtra",
            "Rohtak, Haryana",
            "Korba, Chhattisgarh",
            "Bhilwara, Rajasthan",
            "Brahmapur, Odisha",
            "Muzaffarpur, Bihar",
            "Ahmednagar, Maharashtra",
            "Mathura, Uttar Pradesh",
            "Kollam, Kerala",
            "Avadi, Tamil Nadu",
            "Kadapa, Andhra Pradesh",
            "Sambalpur, Odisha",
            "Bilaspur, Chhattisgarh",
            "Shahjahanpur, Uttar Pradesh",
            "Satara, Maharashtra",
            "Bijapur, Karnataka",
            "Rampur, Uttar Pradesh",
            "Shivamogga, Karnataka",
            "Chandrapur, Maharashtra",
            "Junagadh, Gujarat",
            "Thrissur, Kerala",
            "Alwar, Rajasthan",
            "Bardhaman, West Bengal",
            "Kulti, West Bengal",
            "Kakinada, Andhra Pradesh",
            "Nizamabad, Telangana",
            "Parbhani, Maharashtra",
            "Tumkur, Karnataka",
            "Hisar, Haryana",
            "Ozhukarai, Puducherry",
            "Bihar Sharif, Bihar",
            "Panipat, Haryana",
            "Darbhanga, Bihar",
            "Bally, West Bengal",
            "Aizawl, Mizoram",
            "Dewas, Madhya Pradesh",
            "Ichalkaranji, Maharashtra",
            "Tirupati, Andhra Pradesh",
            "Karnal, Haryana",
            "Bathinda, Punjab",
            "Jalna, Maharashtra",
            "Barasat, West Bengal",
            "Kirari Suleman Nagar, Delhi",
            "Purnia, Bihar",
            "Satna, Madhya Pradesh",
            "Mau, Uttar Pradesh",
            "Sonipat, Haryana",
            "Farrukhabad, Uttar Pradesh",
            "Sagar, Madhya Pradesh",
            "Rourkela, Odisha",
            "Durg, Chhattisgarh",
            "Imphal, Manipur",
            "Ratlam, Madhya Pradesh",
            "Hapur, Uttar Pradesh",
            "Arrah, Bihar",
            "Anantapur, Andhra Pradesh",
            "Karimnagar, Telangana",
            "Etawah, Uttar Pradesh",
            "Ambarnath, Maharashtra",
            "North Dumdum, West Bengal",
            "Bharatpur, Rajasthan",
            "Begusarai, Bihar",
            "New Delhi, Delhi",
            "Gandhidham, Gujarat",
            "Baranagar, West Bengal",
            "Tiruvottiyur, Tamil Nadu",
            "Puducherry, Puducherry",
            "Sikar, Rajasthan",
            "Thoothukudi, Tamil Nadu",
            "Rewa, Madhya Pradesh",
            "Mirzapur, Uttar Pradesh",
            "Raichur, Karnataka",
            "Pali, Rajasthan",
            "Ramagundam, Telangana",
            "Haridwar, Uttarakhand",
            "Vijayanagaram, Andhra Pradesh",
            "Katihar, Bihar",
            "Nagercoil, Tamil Nadu",
            "Sri Ganganagar, Rajasthan",
            "Karawal Nagar, Delhi",
            "Mango, Jharkhand",
            "Thanjavur, Tamil Nadu",
            "Bulandshahr, Uttar Pradesh",
            "Uluberia, West Bengal",
            "Murwara, Madhya Pradesh",
            "Sambhal, Uttar Pradesh",
            "Singrauli, Madhya Pradesh",
            "Nadiad, Gujarat",
            "Secunderabad, Telangana",
            "Naihati, West Bengal",
            "Yamunanagar, Haryana",
            "Bidhan Nagar, West Bengal",
            "Pallavaram, Tamil Nadu",
            "Bidar, Karnataka",
            "Munger, Bihar",
            "Panchkula, Haryana",
            "Burhanpur, Madhya Pradesh",
            "Raurkela Industrial Township, Odisha",
            "Kharagpur, West Bengal",
            "Dindigul, Tamil Nadu",
            "Gandhinagar, Gujarat",
            "Hospet, Karnataka",
            "Nangloi Jat, Delhi",
            "Malda, West Bengal",
            "Ongole, Andhra Pradesh",
            "Deoghar, Jharkhand",
            "Chapra, Bihar",
            "Haldia, West Bengal",
            "Khandwa, Madhya Pradesh",
            "Nandyal, Andhra Pradesh",
            "Morena, Madhya Pradesh",
            "Amroha, Uttar Pradesh",
            "Anand, Gujarat",
            "Bhind, Madhya Pradesh",
            "Bhalswa Jahangir Pur, Delhi",
            "Madhyamgram, West Bengal", "Bhiwani, Haryana",
            "Berhampur, Odisha",
            "Ambala, Haryana",
            "Morbi, Gujarat",
            "Fatehpur, Uttar Pradesh",
            "Raebareli, Uttar Pradesh",
            "Khora, Uttar Pradesh",
            "Chittoor, Andhra Pradesh",
            "Bhusawal, Maharashtra",
            "Orai, Uttar Pradesh",
            "Bahraich, Uttar Pradesh",
            "Phusro, Jharkhand",
            "Vellore, Tamil Nadu",
            "Mehsana, Gujarat",
            "Raiganj, West Bengal",
            "Sirsa, Haryana",
            "Danapur, Bihar",
            "Serampore, West Bengal",
            "Sultan Pur Majra, Delhi",
            "Guna, Madhya Pradesh",
            "Jaunpur, Uttar Pradesh",
            "Panvel, Maharashtra",
            "Shivpuri, Madhya Pradesh",
            "Surendranagar Dudhrej, Gujarat",
            "Unnao, Uttar Pradesh",
            "Chinsurah, West Bengal",
            "Alappuzha, Kerala",
            "Kottayam, Kerala",
            "Machilipatnam, Andhra Pradesh",
            "Shimla, Himachal Pradesh",
            "Adoni, Andhra Pradesh",
            "Udupi, Karnataka",
            "Tenali, Andhra Pradesh",
            "Proddatur, Andhra Pradesh",
            "Saharsa, Bihar",
            "Hindupur, Andhra Pradesh",
            "Sasaram, Bihar",
            "Hajipur, Bihar",
            "Bhimavaram, Andhra Pradesh",
            "Dehri, Bihar",
            "Madanapalle, Andhra Pradesh",
            "Siwan, Bihar",
            "Bettiah, Bihar",
            "Guntakal, Andhra Pradesh",
            "Srikakulam, Andhra Pradesh",
            "Motihari, Bihar",
            "Dharmavaram, Andhra Pradesh",
            "Gudivada, Andhra Pradesh",
            "Bagaha, Bihar",
            "Palwal, Haryana",
            "Kadiri, Andhra Pradesh",
            "Sitamarhi, Bihar",
            "Jamalpur, Bihar",
            "Marmagao, Goa",
            "Hoskote, Karnataka",
            "Adilabad, Telangana",
            "Siddipet, Telangana",
            "Karaikudi, Tamil Nadu",
            "Kishanganj, Bihar",
            "Jamui, Bihar",
            "Ballia, Uttar Pradesh",
            "Kavali, Andhra Pradesh",
            "Tadepalligudem, Andhra Pradesh",
            "Amaravati, Andhra Pradesh",
            "Buxar, Bihar",
            "Jehanabad, Bihar",
            "Aurangabad, Bihar"
    );

    @GetMapping("/cities")
    public ResponseEntity<List<String>> getCities(@RequestParam String query) {
        if (query == null || query.length() < 3) {
            return ResponseEntity.badRequest().body(new ArrayList<>()); // Or return an empty list
        }

        String lowerCaseQuery = query.toLowerCase();
        List<String> filteredCities = indianCities.stream()
                .filter(city -> city.toLowerCase().contains(lowerCaseQuery))
                .limit(5) // Limit to top 5 results
                .collect(Collectors.toList());

        return ResponseEntity.ok(filteredCities);
    }
}

